USE [SAP_TEST]
GO

/****** Object:  Table [dbo].[ORDERS]    Script Date: 2021-04-02 오후 5:58:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ORDERS](
	[주문번호] [int] NOT NULL,
	[주문고객] [nchar](20) NULL,
	[주문제품] [nchar](10) NULL,
	[수량] [int] NULL,
	[단가] [int] NULL,
	[주문일자] [nchar](10) NULL,
 CONSTRAINT [PK_ORDERS] PRIMARY KEY CLUSTERED 
(
	[주문번호] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_ORDERS_CUST] FOREIGN KEY([주문고객])
REFERENCES [dbo].[CUST] ([고객아이디])
GO

ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [FK_ORDERS_CUST]
GO


DROP TABLE [dbo].[ORDERS]
GO

DROP TABLE [dbo].[CUST]
GO

DROP TABLE [dbo].[PRDS]
GO
