CREATE TABLE TESTTABLE002
(
	VEND_ID		VARCHAR(10) NOT NULL,
	VEND_EMP	VARCHAR(10) NOT NULL,
	VEND_VAL	INT			DEFAULT 0,
	PRIMARY KEY(VEND_ID),
	FOREIGN KEY(VEND_EMP) REFERENCES TESTTABLE(CUST_ID)
);