CREATE DATABASE TESTDB

CREATE TABLE CUSTOMER(
	CUST_CD		VARCHAR(10) NOT NULL,
	CUST_NM		VARCHAR(20) NOT NULL,
	CUST_AGE	INT			DEFAULT 0,
	CUST_LVL	VARCHAR(10) NOT NULL,
	CUST_JOB	VARCHAR(20) NOT NULL,
	CUST_POINT	INT			DEFAULT 0,
	PRIMARY KEY	(CUST_CD),
	CHECK (CUST_AGE >= 60)
);

CREATE TABLE PRODUCTS(
	PROD_CD		VARCHAR(10)		NOT NULL,
	PROD_NM		VARCHAR(20)		NOT NULL,
	PROD_QY		INT				DEFAULT 0,
	PROD_PRI	DECIMAL(18,4)	DEFAULT 0,
	PROD_VEND	VARCHAR(20)
	PRIMARY KEY (PROD_CD),
	CHECK(PROD_QY >=0 AND PROD_QY <=10000)
);

CREATE TABLE ORDERS(
	ORD_CD		VARCHAR(10)		NOT NULL,
	CUST_CD		VARCHAR(10)		NOT NULL,
	PROD_CD		VARCHAR(10)		DEFAULT 0,
	ORDER_QTY	INT				DEFAULT 0,
	ORDER_ADD	VARCHAR(20),
	ORDER_REGDT	DATETIME DEFAULT GETDATE(),
	PRIMARY KEY	(ORD_CD),
	FOREIGN KEY(CUST_CD) REFERENCES CUSTOMER(CUST_CD),
	FOREIGN KEY(PROD_CD) REFERENCES PRODUCTS(PROD_CD),

	CHECK(ORDER_QTY >= 0 AND ORDER_QTY <= 10000)
);

