CREATE TABLE TESTTABLE002
(
	VEND_ID		VARCHAR(10) NOT NULL,
	VEND_EMP	VARCHAR(20) NOT NULL,
	VEND_VAL	INT			DEFAULT 0,
	PRIMARY KEY(VEND_ID),
	FOREIGN KEY(VEND_EMP) REFERENCES TESTTABLE(CUST_ID)
);

INSERT INTO TESTTABLE002
VALUES
('1001', 'A', 1000),
('1002', 'B', 1000),
('1003', 'C', 1000),
('1004', 'D', 1000),
('1005', 'E', 1000);

SELECT *
FROM TESTTABLE,TESTTABLE002

SELECT *
FROM 

UPDATE TESTTABLE
SET CUST_POINT = 2000
WHERE CUST_ID = 'B'

SELECT *
FROM TESTTABLE AS A
	LEFT OUTER JOIN TESTTABLE002 AS B
	ON A.CUST_ID = B.VEND_EMP

SELECT *
FROM TESTTABLE AS A
	LEFT OUTER JOIN TESTTABLE002 AS B
	ON A.CUST_ID = B.VEND_EMP
WHERE CUST_ID = 'B'

SELECT CUST_ID, SUM(CUST_POINT) AS CUST_POINT_TOTAL, VEND_ID,VEND_VAL
FROM TESTTABLE AS A
LEFT OUTER JOIN TESTTABLE002 AS B
ON A.CUST_ID = B.VEND_EMP
GROUP BY
CUST_ID
,VEND_ID
,VEND_VAL

SELECT CUST_ID, CUST_POINT, VEND_ID, VEND_VAL
FROM TESTTABLE002 B
LEFT OUTER JOIN TESTTABLE A
ON B.VEND_EMP = A.CUST_ID
