CREATE TABLE CUST_01(
	CUST_ID		VARCHAR(20)		NOT NULL,
	CUST_NM		VARCHAR(10)		NOT NULL,
	CUST_AGE	INT				DEFAULT 14,
	CUST_LVL	VARCHAR(10)		NOT NULL,
	CUST_JOB	VARCHAR(20),
	CUST_POINT	INT				DEFAULT 0,
	PRIMARY KEY(CUST_ID),
--	ON DELETE CASCADE 
--	ON UPDATE CASCADE
	CHECK(CUST_AGE>=14)
);

CREATE TABLE PROD_01(
	PROD_CD	CHAR(3)  NOT NULL,
	PROD_NM	VARCHAR(20),
	PROD_ST	INT,
	PROD_PRI INT,
	PROD_VEND	VARCHAR(20),
	PRIMARY KEY(PROD_CD),
	CHECK(PROD_ST>=0 AND PROD_ST<=10000)
);

CREATE TABLE ORDER_01(
	ORD_CD	CHAR(3)	NOT	NULL,
	CUST_ID	VARCHAR(20),
	PROD_CD CHAR(3),
	ORD_QTY INT,
	ORD_ADD VARCHAR(30),
	ORD_REGDT DATETIME DEFAULT GETDATE()
	PRIMARY KEY(ORD_CD),
	FOREIGN KEY(CUST_ID) REFERENCES CUST_01(CUST_ID), --부모가 CUSTOMER CUST_ID, 여기 있는 친구 외에는 못 들어간다.
	FOREIGN KEY(PROD_CD) REFERENCES PROD_01(PROD_CD)
);

ALTER TABLE ORDER_01 ADD ORD_OUTDT VARCHAR(20) DEFAULT GETDATE()
--GETDATE 속성 삭제하려면 디자인으로 들어가서 DEFAULT 값을 지우고 조작하면 됨


--DB 체크 MASTER  

--FK로 묶는 이유: 참조하는 대상 외에 다른 값이 못 들어가도록 하기 위해. 부모쪽에 있는 데이터 외에 입력이 불가능해야 거를 수 있어서